- name: Ensure application is deployed
  hosts: prod
  become: true
  tasks:
    - block:
        - name: Check that you can connect to webpage
          uri:
            url: http://54.174.250.215
          retries: 8
          delay: 15

        - name: Check webservice application production
          uri:
            url: http://54.174.250.215/health
            method: GET
          retries: 8
          delay: 15
      tags:
        - prod
