---
- name: deploy to private registry
  hosts: prod
  become: true
  tasks:
    - block:
        - name: Create docker network
          docker_network:
            name: myregistry
          tags:
            - prod
        - name: pull an image
          docker_image:
            name: registry:2
            source: pull
          tags:
            - prod

        - name: Deploy private Registry
          docker_container:
            name: registry
            image: registry:2
            state: started
            networks:
              - name: myregistry
            ports:
              - "5000:5000"
            restart_policy: "always"
          tags:
            - prod

        - name: Deploy Registry-UI
          docker_container:
            name: registry_ui
            image: joxit/docker-registry-ui:static
            state: started
            networks:
              - name: myregistry
            ports:
              - "4002:80"
            restart_policy: "always"
            env:
              REGISTRY_URL: "http://registry:5000"
              DELETE_IMAGES: "true"
              REGISTRY_TITLE: "MY_REGISTRY"
          tags:
            - prod
